## CHANGE Change this to your dependency name
name: LogiTech

## CHANGE Change this to your name
author: matl114

## CHANGE This is an introduction to your plugin
description: Logical Slimefun4-Addon To Make A Better World

## CHANGE points to the main class of your JavaPlugin.
main: me.matl114.logitech.MyAddon

## You can change it to your project repository address, or your personal website. You can also remove this project.
website: https://github.com/m1919810/LogiTech

## The value will be automatically replaced at build time with the version defined in pom.xml.
## Do not change this line.
version: ${project.version}

## This is the minimum MC version required to run the dependency.
api-version: '1.20'

## To specify Slimefun as a dependency, you must

depend:
- Slimefun
- GuizhanLibPlugin
softdepend:
- InfinityExpansion
- Networks

commands:
  logitech:
    description: basic logitech command
    aliases: lc
    usage: 'ask the author,pls.I dont think theres a need for you to use these commands'

permissions:
  logitech.command.op:
    description: Allows you to use operator commands
    default: op
  logitech.shell.root:
    description: Allows you to open root shell without password
    default: op
  logitech.shell.test:
    description: Allows you to use test operator tools
    default: op
